### ISSUE TITLE
Segmentation fault on start (v0.24 & v0.25) v0.23 works for me.

### ISSUE THREAD

**Issue by kaefert** [EUA/wxHexEditor#155]
Hi there!

I'm on a Manjaro (Arch) KDE laptop.

I first tried the [wxhexeditor 0.24-4 aur package](https://aur.archlinux.org/packages/wxhexeditor) after getting a Segfault on trying to start it after installation I tried [wxhexeditor-git 0.25.r86.gd738638-1](https://aur.archlinux.org/packages/wxhexeditor-git) which behaved the same way.

Then I downloaded the v0.24 linux binary from https://sourceforge.net/projects/wxhexeditor/ which had the same issue and finally I landed on v0.23 from the same URL which worked fine.

If I can help in tracing the problem please tell me how.

**Comment by EUA** [comment]
Hello, sorry for lateness. In vacation this days.

What could be wrong? Probably previous preferences make issue.
Please delete ~/.wxHexEditor file and try again.

I am Arch user, at my desktop and use Manjaro at my laptop too. :D
Now will try to load wxHexEditor and test if it broken or not.

**Comment by EUA** [comment]
Now I installed 0.25-git version and under plasma-wayland compositor and ... yeah resizing is little jerky, probably due wayland, but there are no segmentation fault at all...

Please delete previous configuration file. Probably it's the main issue.

**Comment by kaefert** [comment]
hmm, strange, I just retested 0.25-git via aur package and deleted the ~/.wxHexEditor file (contained only "Language=") before starting it but I stll get a segmentation fault after the application flashing the license agreement popup for 2/10th of a second.

**Comment by EUA** [comment]
Himm.
This is interesting.
If you could fetch git trunk and use code::block to compile under debug mode, you can easily spot where the issue is...
Or using git bisect will show which commit is responsible for the issue.
I really can't help since I can't reproduce the segmentation fault.

**Comment by kaefert** [comment]
Sorry, but can you be a bit more specific what I need to do?

What I tried so far:
```
git clone https://github.com/EUA/wxHexEditor.git
cd wxHexEditor
make
```

Which resulted in:
```
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -DNDEBUG src/HexEditorGui.cpp -o src/HexEditorGui.o
/bin/sh: wx-config: command not found
src/HexEditorGui.cpp:8:10: fatal error: wx/wxprec.h: No such file or directory
    8 | #include "wx/wxprec.h"
      |          ^~~~~~~~~~~~~
```

**Comment by EUA** [comment]
your path has wx-config-gtk3 but not wx-config
Please build with this command:
`make WXCONFIG=wx-config-gtk3`

**Comment by kaefert** [comment]
well that's strange. built manually like that it worked as it should.
I rebuilt the AUR package and this time it also worked as it should.
So the only version which still gives me a Segfault is the one from wxHexEditor-v0.24-Linux_x86_64.tar.xz

**Comment by EUA** [comment]
Ah, that's static build and static builds in linux has such an issues every time due updated libc etc.
Nothing to worry about it.
:)
